---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: smart-exporter
  namespace: openshift-monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: smart-exporter
  namespace: openshift-monitoring
  labels:
    apps: smart-exporter
spec:
  selector:
    apps: smart-exporter
  ports:
  - port: 9110
    name: http
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: smart-exporter
  namespace: openshift-monitoring
  labels:
    apps: smart-exporter
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        apps: smart-exporter
    spec:
      serviceAccountName: smart-exporter 
      hostIPC: true
      hostNetwork: true
      hostPID: true
      containers:
      - image: "containersai/smart_exporter:latest"
        securityContext:
          privileged: true
        name: smart-exporter
        ports:
        - containerPort: 9110
          hostPort: 9110
          name: http
          protocol: TCP
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 50Mi
            cpu: 200m
        volumeMounts:
        - name: dev
          readOnly:  true
          mountPath: /host/dev
        env:
        - name: "INTERVAL_TIME"
          value: "10"
        - name: "HOSTDEV_PATH"
          value: "/host/dev"
      volumes:
      - name: dev
        hostPath:
          path: /dev
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: smart-exporter
  name: smart-exporter
  namespace: openshift-monitoring
spec:
  endpoints:
  - interval: 30s
    port: http
    scheme: http
  jobLabel: smart-exporter
  namespaceSelector: {}
  selector:
    matchLabels:
      apps: smart-exporter