---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-exporter
  namespace: alameda-monitoring
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: daemonset-example
  namespace: alameda-monitoring
spec:
  template:
    metadata:
      labels:
        app: daemonset-example
      annotations:
        alameda/scrape: "true"
    spec:
      hostNetwork: true # okd
      serviceAccountName: node-exporter
      containers:
      - name: node-exporter
        image: prom/node-exporter:v0.14.0
        args:
        - "--collector.procfs=/host/proc"
        - "--collector.sysfs=/host/sys"
        - "-web.listen-address=:9100"  
        ports:
        - containerPort: 9100 
          hostPort: 9100 
          name: scrape
          protocol: TCP
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 50Mi
            cpu: 200m
        volumeMounts:
        - name: proc
          readOnly:  true
          mountPath: /host/proc
        - name: sys
          readOnly: true
          mountPath: /host/sys
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: dev
        hostPath:
          path: /dev