---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: smart-exporter
  namespace: alameda-monitoring
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: smart-exporter
  namespace: alameda-monitoring
  labels:
    app: smart-exporter
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: smart-exporter
      annotations:
        alameda/scrape: "true"
    spec:
      serviceAccountName: smart-exporter 
      hostIPC: true
      hostNetwork: true
      hostPID: true
      containers:
      - image: "containersai/smart_exporter:latest"
        securityContext:
          privileged: true
        name: smart-exporter
        ports:
        - containerPort: 9110
          hostPort: 9110
          name: smart-scrape
          protocol: TCP
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 50Mi
            cpu: 200m
        volumeMounts:
        - name: dev
          readOnly:  true
          mountPath: /host/dev
        env:
        - name: "INTERVAL_TIME"
          value: "10"
        - name: "HOSTDEV_PATH"
          value: "/host/dev"
      volumes:
      - name: dev
        hostPath:
          path: /dev
