# node-exporter is an optional component that collects host level metrics from the nodes 
# in the cluster. This group of resources will require the 'hostaccess' level of privilege, which
# should only be granted to namespaces that administrators can access.
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: prometheus-node-exporter
  # You must grant hostaccess via: oadm policy add-scc-to-user -z prometheus-node-exporter hostaccess
  # in order for the node-exporter to access the host network and mount /proc and /sys from the host
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/scrape: "true"
    labels:
      app: prometheus-node-exporter
    name: prometheus-node-exporter
  spec:
    clusterIP: None
    ports:
    - name: scrape
      port: 9100
      protocol: TCP
      targetPort: 9100
    - name: smart-scrape
      port: 9110
      protocol: TCP
      targetPort: 9110
    selector:
      app: prometheus-node-exporter
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    name: prometheus-node-exporter
    labels:
      app: prometheus-node-exporter
      role: monitoring
  spec:
    updateStrategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: prometheus-node-exporter
          role: monitoring
        name: prometheus-exporter
      spec:
        serviceAccountName: prometheus-node-exporter
        hostDirVolumePlugin: true
        hostIPC: true
        hostNetwork: true
        hostPID: true
        privilegedContainer: true
        containers:
        # smart-exporter plugin
        - image: "docker-registry.default.svc:5000/monitoring/smart-exporter:latest"
          securityContext:
            privileged: true
          imagePullPolicy: Always
          name: smart-exporter
          ports:
          - containerPort: 9110
            hostPort: 9110
            name: smart-scrape
            protocol: TCP
          resources:
            requests:
              memory: 30Mi
              cpu: 100m
            limits:
              memory: 50Mi
              cpu: 200m
          volumeMounts:
          - name: dev
            readOnly:  true
            mountPath: /host/dev
          env:
          - name: "INTERVAL_TIME"
            value: "10"
          - name: "HOSTDEV_PATH"
            value: "/host/dev"
        # node-exporter
        - image: openshift/prometheus-node-exporter:v0.14.0
          args:
          - "--collector.procfs=/host/proc"
          - "--collector.sysfs=/host/sys"
          name: node-exporter
          ports:
          - containerPort: 9100
            hostPort: 9100
            name: scrape
            protocol: TCP
          resources:
            requests:
              memory: 30Mi
              cpu: 100m
            limits:
              memory: 50Mi
              cpu: 200m
          volumeMounts:
          - name: proc
            readOnly:  true
            mountPath: /host/proc
          - name: sys
            readOnly: true
            mountPath: /host/sys
        volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: dev
          hostPath:
            path: /dev
